before_script:
  - julia -e 'using InteractiveUtils;
              versioninfo()'

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

stages:
  - test
  - postprocess


## testing

.test_template: &test_template
  script:
    - mkdir $JULIA_DEPOT_PATH # Pkg3.jl#325
    - julia --project-e "using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);"
  artifacts:
    paths:
      - Manifest.toml
      - .julia/
      - src/*.cov

test:v0.7:
  stage: test
  image: juliagpu/julia:v0.7-cuda
  <<: *test_template

test:dev:
  stage: test
  image: juliagpu/julia:dev-cuda
  <<: *test_template


## post-processing

coverage:
  stage: postprocess
  image: juliagpu/julia:v0.7-cuda
  dependencies:
    - test:v0.7
  script:
    - julia --project -e 'using Pkg;
                          Pkg.add("Coverage")'
    - julia --project -e 'using Coverage;
                          cl, tl = get_summary(process_folder());
                          println("(", cl/tl*100, "%) covered");
                          Codecov.submit_local(process_folder(), ".")'
  coverage: '/\(\d+.\d+\%\) covered/'
