.test_template: &test_definition
  script:
    - julia -e 'using InteractiveUtils; versioninfo()'
    # actual testing
    # TODO: `Pkg.build(); Pkg.test(; coverage=true)` once that works
    - julia -e "using Pkg;
                Pkg.develop(\"$CI_PROJECT_DIR\");
                Pkg.build(\"$package\");
                Pkg.test(\"$package\"; coverage=true)"
    # coverage
    - julia -e 'using Pkg; Pkg.add("Coverage")'
    - julia -e 'using Coverage;
                cl, tl = get_summary(process_folder());
                println("(", cl/tl*100, "%) covered");
                Codecov.submit_local(process_folder(), ".")'
    # documentation
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia docs/make.jl
  coverage: '/\(\d+.\d+\%\) covered/'

variables:
  package: 'CUDAnative'

test:dev:
  image: juliagpu/julia:dev
  <<: *test_definition
