.test_template: &pkg2_test_definition
  script:
    - julia -e 'versioninfo()'
    # actual testing
    - julia -e "Pkg.init();
                symlink(\"$CI_PROJECT_DIR\", joinpath(Pkg.dir(), \"$package\"));
                Pkg.resolve();
                Pkg.build(\"$package\");
                Pkg.test(\"$package\"; coverage=true)"

.test_template: &pkg3_test_definition
  script:
    - julia -e 'using InteractiveUtils; versioninfo()'
    # actual testing
    # TODO: `Pkg.build(); Pkg.test(; coverage=true)` once that works
    - julia -e "using Pkg;
                Pkg.develop(\"$CI_PROJECT_DIR\");
                Pkg.build(\"$package\");
                Pkg.test(\"$package\"; coverage=true)"

variables:
  package: 'CUDAapi'

test:0.6:
  image: juliagpu/julia:v0.6
  <<: *pkg2_test_definition

test:0.7:
  image: juliagpu/julia:v0.7
  <<: *pkg3_test_definition
