language: julia

os:
  - linux

julia:
  - 0.6

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true
    - ONLY_LOAD=true

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("CUDAnative")); include(joinpath("docs", "make.jl"))'
