environment:
  matrix:
  - julia_version: 0.7
  - julia_version: latest
  # CUDA versions
  - julia_version: 0.7
    cuda_version: 8.0
  - julia_version: 0.7
    cuda_version: 9.0
  - julia_version: 0.7
    cuda_version: 9.1
  - julia_version: 0.7
    cuda_version: 9.2
  # nightly
  - julia_version: latest
    cuda_version: 8.0

platform:
  - x64

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - powershell .\appveyor.ps1
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
