branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  global:
    DEBUG: true
  matrix:
    # CUDA versions
    - JULIA: 0.6
      CUDA: 8.0
    - JULIA: 0.6
      CUDA: 9.0
    - JULIA: 0.6
      CUDA: 9.1
    - JULIA: 0.6
      CUDA: 9.2
    # nightly
    - JULIA: nightly
      CUDA: 8.0

install:
  - powershell .\appveyor.ps1

build_script:
  # convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"CUDAapi\"); Pkg.build(\"CUDAapi\")"

test_script:
  - C:\julia\bin\julia -e "Pkg.test(\"CUDAapi\")"
