branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  global:
    DEBUG: true
  matrix:
    # CUDA versions
    - JULIA: 0.6
      CUDA: 8.0
    - JULIA: 0.6
      CUDA: 9.0
    # nightly
    - JULIA: nightly
      CUDA: 8.0

# https://help.appveyor.com/discussions/problems/12405-builds-failing-due-to-github-tls-changes
init:
  - ps: new-itemproperty -path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord";
  - ps: new-itemproperty -path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord"

install:
  - powershell .\appveyor.ps1

build_script:
  # convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"CUDAapi\"); Pkg.build(\"CUDAapi\")"

test_script:
  - C:\julia\bin\julia -e "Pkg.test(\"CUDAapi\")"
