branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  JULIA_DEBUG: "CUDAapi"
  matrix:
    # CUDA versions
    - JULIA: 0.7
      CUDA: 8.0
    - JULIA: 0.7
      CUDA: 9.0
    - JULIA: 0.7
      CUDA: 9.1
    - JULIA: 0.7
      CUDA: 9.2
    # nightly
    - JULIA: nightly
      CUDA: 8.0

install:
  - powershell .\appveyor.ps1

build_script:
  - C:\julia\bin\julia -e "using InteractiveUtils;
                           versioninfo();
                           using Pkg;
                           Pkg.instantiate();
                           Pkg.build()"

test_script:
  - C:\julia\bin\julia -e "using Pkg;
                           Pkg.test()"
