# CUDA

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "5a22487594aff21b7f2ea6884850cadccb2181a6"
os = "macos"
lazy = true

    [[CUDA100.download]]
    sha256 = "8b43cde786a87816780ab22596804a9e1b3c322e092f5ff16700a82936726a90"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+3/CUDA.v10.0.130.x86_64-apple-darwin.tar.gz"

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "b0592237d8a9a7dd5f9c8efac9ddda71cc901f69"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA100.download]]
    sha256 = "bdd8cb68a1d577a67eec06ae184669cf729bf6054b02850246b8b6010a64ed34"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+3/CUDA.v10.0.130.x86_64-linux-gnu.tar.gz"

[[CUDA100]]
arch = "x86_64"
git-tree-sha1 = "bed5722a911f3ec6132a68a9fe10ff396faaaf54"
os = "windows"
lazy = true

    [[CUDA100.download]]
    sha256 = "2e7906f5278935fbf58814591af6ff7400495de8b6bdc549b920a268e6febd92"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.0.130+3/CUDA.v10.0.130.x86_64-w64-mingw32.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "e074f724be185f516f506a28183af43d3542f8b9"
os = "macos"
lazy = true

    [[CUDA101.download]]
    sha256 = "88b7a9504d092f0a420d02316a5544bff8b73ed52c705a33a02940318f5fbe39"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+5/CUDA.v10.1.243.x86_64-apple-darwin.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "f049c2824a217dc29dbf657e5cdf0f8adafca77a"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA101.download]]
    sha256 = "2223142ae8f2a99def1a1a5f6eae6f34e70ecccb396c2a3bcd6f2cd2f0b03a64"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+5/CUDA.v10.1.243.x86_64-linux-gnu.tar.gz"

[[CUDA101]]
arch = "x86_64"
git-tree-sha1 = "4f356e2a5ff36fb141b7a41bd40a82522b3ff590"
os = "windows"
lazy = true

    [[CUDA101.download]]
    sha256 = "ec69a036296d9348ca044512417f26a3eb0a08d647dd754024525bd1df7c6a04"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.1.243+5/CUDA.v10.1.243.x86_64-w64-mingw32.tar.gz"

[[CUDA102]]
arch = "x86_64"
git-tree-sha1 = "4902a30cc1c0dd4d42aa245c4e2d2d9e54e7cbc0"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA102.download]]
    sha256 = "19e2a92205ce911029881622b57dfb0e8f5e54b37a04e12432d716910c577d5b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+5/CUDA.v10.2.89.x86_64-linux-gnu.tar.gz"

[[CUDA102]]
arch = "x86_64"
git-tree-sha1 = "28f01e29895066664f0a9b7b74174239f7c127ff"
os = "windows"
lazy = true

    [[CUDA102.download]]
    sha256 = "808f93e5b410c9782352d49c58ca12290b1f9402a56b6c2fe003f0d24bdb981c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v10.2.89+5/CUDA.v10.2.89.x86_64-w64-mingw32.tar.gz"

[[CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "b22672705ca4f00c784a3f9d58619408d4af9de0"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA110.download]]
    sha256 = "e86a67aa8b1b2cd73d78572401efa75f9bb26f6a259f12d0471c64b74fbe204f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+3/CUDA.v11.0.3.powerpc64le-linux-gnu.tar.gz"

[[CUDA110]]
arch = "x86_64"
git-tree-sha1 = "6b1a60793e5e98abdcfc3724cfa22b2a5348dc09"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA110.download]]
    sha256 = "520e690529f67afe6aabdd8d18dc34d18acf5020cb3dc1fd4e904998d9e17aba"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+3/CUDA.v11.0.3.x86_64-linux-gnu.tar.gz"

[[CUDA110]]
arch = "x86_64"
git-tree-sha1 = "2d09da4d71a0762750dee0861e28029d38b08d1e"
os = "windows"
lazy = true

    [[CUDA110.download]]
    sha256 = "d11ca219e9b91725c6677f36b339459d149ffdcfa3f5e51928fb133158caa15a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.0.3+3/CUDA.v11.0.3.x86_64-w64-mingw32.tar.gz"

[[CUDA111]]
arch = "powerpc64le"
git-tree-sha1 = "44dba03dc848a148c9d2430354bf7e52e216364c"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA111.download]]
    sha256 = "ac85a364080ea8b97e77fb83967046c54099f7c63769577fa39a1311b68add81"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.1+2/CUDA.v11.1.1.powerpc64le-linux-gnu.tar.gz"

[[CUDA111]]
arch = "x86_64"
git-tree-sha1 = "48c41dccb8db0c9aa9483267cb33719207abe4c1"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA111.download]]
    sha256 = "b7242ce10b3fb06d886725209d5b19d565c15c7e244eb84b50262f281a04291c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.1+2/CUDA.v11.1.1.x86_64-linux-gnu.tar.gz"

[[CUDA111]]
arch = "x86_64"
git-tree-sha1 = "ad4cf0816c2c327477c512f476649bfde7ada206"
os = "windows"
lazy = true

    [[CUDA111.download]]
    sha256 = "026a92bcb8d7a5ff6f2e6e262ed8d8387164314941f0dc1b3228e383e04a60a0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.1.1+2/CUDA.v11.1.1.x86_64-w64-mingw32.tar.gz"

[[CUDA112]]
arch = "powerpc64le"
git-tree-sha1 = "205075090ca78a68358e4613a444e56ddf5333d3"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA112.download]]
    sha256 = "f70b74ddb1586d981c06ab94111e5b5616271d788292ee5be66d3ccff758c3c9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.2.0+1/CUDA.v11.2.0.powerpc64le-linux-gnu.tar.gz"

[[CUDA112]]
arch = "x86_64"
git-tree-sha1 = "e99dab5d7bdf5b60da265bae5e949189d907a56b"
libc = "glibc"
os = "linux"
lazy = true

    [[CUDA112.download]]
    sha256 = "8227d1a4fa12aa3effb1c2539b62af46cd3182c5c71c4cdd691481f3bfda3027"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.2.0+1/CUDA.v11.2.0.x86_64-linux-gnu.tar.gz"

[[CUDA112]]
arch = "x86_64"
git-tree-sha1 = "f73affa53f315e145ba5693767c9ab71d0ebde50"
os = "windows"
lazy = true

    [[CUDA112.download]]
    sha256 = "e1eb76c3553855dfd584bf0f16b43e14c95839fc1b5d0cfa27569d64a51b3802"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_jll.jl/releases/download/CUDA-v11.2.0+1/CUDA.v11.2.0.x86_64-w64-mingw32.tar.gz"


# CUDNN

## v8.0

[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "ef45f9aaa18e23f1360eb6cb06c89ead81752f02"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "b72bac08f0c878a350b35c69356a85a5cd578b0e457ac68c9989f6bf055b9880"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.4+0/CUDNN_CUDA101.v8.0.4.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "5d3b42f300c3a87ab8858e86aa81f9caf4b12d1a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA101.download]]
    sha256 = "a40f9e83864b339af28a7012e9f027b932aa0a882a7dd2a63bb9a94fc58e111e"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.4+0/CUDNN_CUDA101.v8.0.4.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "29e0f0db94f0a4aa539ffc8593dd07f0f209965c"
lazy = true
os = "windows"

    [[CUDNN_CUDA101.download]]
    sha256 = "ac23cbb9ccde477ec2fad4d2efa1b891c8c6079de5df06f6f9d7f4871343d23f"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA101_jll.jl/releases/download/CUDNN_CUDA101-v8.0.4+0/CUDNN_CUDA101.v8.0.4.x86_64-w64-mingw32.tar.gz"

## v8.1

[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "fc5abe954be532ce9bf6882b3cfb906a880e33e3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "5130ea7495e2d20e1c9894460fa6b2cca623b8ab5aadeb1e144326e416345bbd"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.1.0+0/CUDNN_CUDA102.v8.1.0.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "4dfab62984ed08dc96d08d92d328cb7a0ded0bb2"
lazy = true
os = "windows"

    [[CUDNN_CUDA102.download]]
    sha256 = "3ae0ae5feb75ac26a7a35d40800af3384ee6ccae45fd74d66a004e6d1cee39ca"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.1.0+0/CUDNN_CUDA102.v8.1.0.x86_64-w64-mingw32.tar.gz"


[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "2ff87587f59f8a1373db3bf4a483e7eed75dc22f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "0b2a8869f6b325c565dc9a04ca0f99e5d261ed4b70808523c7035d56f1d4d584"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.1.0+0/CUDNN_CUDA110.v8.1.0.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "1d3f5c46ca50d7f01bce7eccfd830e20f51fd095"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA110.download]]
    sha256 = "e0da2e165d78b3082eacc9f13ef5e2ee45ad2a7c35586072ac7cfb87a34f7e29"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.1.0+0/CUDNN_CUDA110.v8.1.0.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "3ba658f7d7427dfdf4ae974828aa00daa9a2bae5"
lazy = true
os = "windows"

    [[CUDNN_CUDA110.download]]
    sha256 = "f29e35b9a4139e0a198065bc3e3a2f46d5be678a44221d3065e5889a7adb010d"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA110_jll.jl/releases/download/CUDNN_CUDA110-v8.1.0+0/CUDNN_CUDA110.v8.1.0.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "ce6e90dba6e6825de312a6480b74e0a7d741d969"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA111.download]]
    sha256 = "46ccd1d9f7bb87f914a414fafc6d904719a838d339a581bbc700959c986510e4"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA111_jll.jl/releases/download/CUDNN_CUDA111-v8.1.0+0/CUDNN_CUDA111.v8.1.0.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA111]]
arch = "powerpc64le"
git-tree-sha1 = "23278bf971a8605139651f9d3b3dca620b6677dc"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA111.download]]
    sha256 = "bfb64f113e667ff9ae44d3904c7bb0773a757f6dd2f32930f8a27cc5850da231"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA111_jll.jl/releases/download/CUDNN_CUDA111-v8.1.0+0/CUDNN_CUDA111.v8.1.0.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "20a1d89b5cd8011ef960ccefb480a7406ef187c8"
lazy = true
os = "windows"

    [[CUDNN_CUDA111.download]]
    sha256 = "735d360d25bf0803582c07bab50c721ce106854883e84b7ab87d509ff9314316"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA111_jll.jl/releases/download/CUDNN_CUDA111-v8.1.0+0/CUDNN_CUDA111.v8.1.0.x86_64-w64-mingw32.tar.gz"

[[CUDNN_CUDA112]]
arch = "x86_64"
git-tree-sha1 = "2791d15fdc61f6355c03ac287ab875e53c84cfbf"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA112.download]]
    sha256 = "2979ba21be3bf3cfe058f98b34666ebe1d9c2373aa8e4439c79d39c9c06b3046"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA112_jll.jl/releases/download/CUDNN_CUDA112-v8.1.0+0/CUDNN_CUDA112.v8.1.0.x86_64-linux-gnu.tar.gz"

[[CUDNN_CUDA112]]
arch = "powerpc64le"
git-tree-sha1 = "e15dc5d20d977d01e4563319804e317aecc0a82e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA112.download]]
    sha256 = "6b59efffa74009f8a91509ef0a583f60e4729bcba1645248d1443e2806ea56ae"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA112_jll.jl/releases/download/CUDNN_CUDA112-v8.1.0+0/CUDNN_CUDA112.v8.1.0.powerpc64le-linux-gnu.tar.gz"

[[CUDNN_CUDA112]]
arch = "x86_64"
git-tree-sha1 = "faf825daf9a28e057e0215da7f05f1992aca4ee5"
lazy = true
os = "windows"

    [[CUDNN_CUDA112.download]]
    sha256 = "badaa798117375a60d3d675187c581f36d60e7dc4bab58edee773cc961249388"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA112_jll.jl/releases/download/CUDNN_CUDA112-v8.1.0+0/CUDNN_CUDA112.v8.1.0.x86_64-w64-mingw32.tar.gz"


# CUTENSOR

[[CUTENSOR_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "8fde822e7da9e38f55a0e4134d904dd61aeb6ad0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "3883cb71f49b1d9d9c39d74d2c5a4985f9878b037502c1920061f040ffa6d8bd"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.2+0/CUTENSOR_CUDA101.v1.2.2.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA101]]
arch = "powerpc64le"
git-tree-sha1 = "49c3b4c6edc6f59b2093a760299ba602cd83509a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "05540522a0481604481e734d47bea453119b14ae3c1b6f6a36348d2d21c2f4a1"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.2+0/CUTENSOR_CUDA101.v1.2.2.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA101]]
arch = "x86_64"
git-tree-sha1 = "c6f183d1d795e69687315dd64759d71d7e8a7932"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA101.download]]
    sha256 = "d922563c3a737f13d2b017da5d3828a9bc468855c13a3ba5040e88c17bd6f3f1"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA101_jll.jl/releases/download/CUTENSOR_CUDA101-v1.2.2+0/CUTENSOR_CUDA101.v1.2.2.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "03cdeb3db858287244c2530d75f0a845b90c48b4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "dbe99a6a5a2f68a2922e2c1006a451cad523a521004409fb80ca883303a85dbf"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "029afc64d39bc2993604c9eb6a15ed8c32f21d57"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "44492dc223f5e7501fec90eb8f35ea68a7feb2284cfdc452d8ee533ddb28475d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "cbd0fa8210b55e659dcbd4a37194812c7edf6be7"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "c8e3e4be487245342ddf111fe487b54c6a2159b212d54277c80d455a184f9b6d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "738c8f6885341191b39addde347d5dfdf0f7f285"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "f3b3dc8907339290567bc536d27a8777b652d518afe36b1aa36eddf56d84173b"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "powerpc64le"
git-tree-sha1 = "aafacc39b2f7802c4f25d1d3ac566928bf68142a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "2e30ef7b737c4dd8743606da2e17dfc4771b259b2e4c169df019c34192c93f40"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA110]]
arch = "x86_64"
git-tree-sha1 = "0c13ab1650b08474165239d1a22ea803466688f3"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA110.download]]
    sha256 = "91c61cbc463aea5b11bc48d6a597804d9ab7a2e5d39e8c05c4d7bdb2643dc6fa"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA110_jll.jl/releases/download/CUTENSOR_CUDA110-v1.2.2+0/CUTENSOR_CUDA110.v1.2.2.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "0ea517d66fb80c2a2a15969bcb11134987747ae9"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA111.download]]
    sha256 = "f52755f5626fc38e238a56e4c6ecd70aac4ffb20641b87292fe6b75f37e1f877"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA111_jll.jl/releases/download/CUTENSOR_CUDA111-v1.2.2+0/CUTENSOR_CUDA111.v1.2.2.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA111]]
arch = "powerpc64le"
git-tree-sha1 = "436ca1a1bb9cb89d9ac567a859a879f539fc0019"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA111.download]]
    sha256 = "6c246216d54c6f8d49d2913274839553f534be0f10094e8a101082d3c5017f71"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA111_jll.jl/releases/download/CUTENSOR_CUDA111-v1.2.2+0/CUTENSOR_CUDA111.v1.2.2.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA111]]
arch = "x86_64"
git-tree-sha1 = "f97bda1f459ad13ad0a9e9c17d0b9a3bc7d631d6"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA111.download]]
    sha256 = "5a09d0aeb14e1621591b90c4109a4877c8fcbc249e60db035aa687683ac37da6"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA111_jll.jl/releases/download/CUTENSOR_CUDA111-v1.2.2+0/CUTENSOR_CUDA111.v1.2.2.x86_64-w64-mingw32.tar.gz"

[[CUTENSOR_CUDA112]]
arch = "x86_64"
git-tree-sha1 = "87ff4afd12dd07e085ead077f7465b365134a6f1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA112.download]]
    sha256 = "04aa433d4dba21b0cf383eb95abbe3f24b7fe0e294857ef016ce78cd43ebdd13"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA112_jll.jl/releases/download/CUTENSOR_CUDA112-v1.2.2+0/CUTENSOR_CUDA112.v1.2.2.x86_64-linux-gnu.tar.gz"

[[CUTENSOR_CUDA112]]
arch = "powerpc64le"
git-tree-sha1 = "6afff0c4f0deafc1038fa79f17a753b6ef1bc854"
lazy = true
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA112.download]]
    sha256 = "694873de718b67c845557bd67fa9ef1175881eab12ccd14ee369b16d776adcdc"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA112_jll.jl/releases/download/CUTENSOR_CUDA112-v1.2.2+0/CUTENSOR_CUDA112.v1.2.2.powerpc64le-linux-gnu.tar.gz"

[[CUTENSOR_CUDA112]]
arch = "x86_64"
git-tree-sha1 = "2c2d0de31f53881c966ab183284e32bf1afbf891"
lazy = true
os = "windows"

    [[CUTENSOR_CUDA112.download]]
    sha256 = "17ac6d40e24b7b6f55947c9026ff796b77c166cf1285a7c375060ac1dfdc4326"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA112_jll.jl/releases/download/CUTENSOR_CUDA112-v1.2.2+0/CUTENSOR_CUDA112.v1.2.2.x86_64-w64-mingw32.tar.gz"
